version: "3.7"
services:

  app:
    build: .
    image: sample_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5273:80"
      - "7273:443"
    depends_on:
        - seq_host
    networks:
      - sample_app_network

  seq_host:
    image: datalust/seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8041:80"
      - "5341:5341"
    networks:
      - sample_app_network

networks:
  sample_app_network:
     name: awesome_logging_network